services:
  frontend:
    build:
      context: ./web
      dockerfile: dockerfile
    ports:
      - 5173:80
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - DATABASE_URL=postgres://kishu:kishu@db:5432/blogdb?sslmode=disable
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: kishu
      POSTGRES_PASSWORD: kishu
      POSTGRES_DB: blogdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
