FROM node:latest AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM golang:1.23-alpine AS middleman
WORKDIR /app
COPY --from=builder /app/dist /app/dist
COPY go.mod ./
RUN go mod download
COPY main.go .
RUN go build -o reactcontainer .
# CMD ["go", "run" ,"main.go"]
# EXPOSE 8081
# CMD ["nginx", "-g", "daemon off;"]

FROM alpine:latest
WORKDIR /app
COPY --from=middleman /app/reactcontainer .
COPY --from=builder /app/dist /app/dist
EXPOSE 8081
CMD ["./reactcontainer"]